### PR TITLE
Update vim-composer.vim

### PR DESCRIPTION
**Pull request by sensorario**
Every time I need to open a file, I use CtrlP plugin to find it inside my filesystem. Sometimes, Nerdtree. But, ... composer knows where files are. With a simply grep, in bash, I can "ask" composer where a file is. In VimL I can get current word. So, ... I'll like to use current word, and pass it to my :grep: and finally, .. I want to open the file returned by grep.
- [x] remove <F6> remap
- [x] introduce default vendor path ./vendor/composer

### CODE REVIEW

**Comment by gianarb** [comment]
ahah good idea :)

**Comment by sensorario** [comment]
This could be a killer feature for me. I need it!!! XD

composer.json KNOWS where autoload is. And also know which PSR rule is applied. For example:

```
"autoload": {
    "psr-0": {
        "": "src/"
    }
},
```

so ...

**Comment by sensorario** [comment]
In this cases, ... maybe a pull request is not a good Idea. Do you think an issue could be better?

**Comment by gianarb** [comment]
PR is good.. Maybe you can improve your first post with a good description of this feature.. :+1: 
And you can call help with VimScipt :)

**Comment by gianarb** [comment]
Oh perfect in my opinion this is a good feature.. Help us user to open file without other plugin..
And help other developers to write our extensions of this plugin..

Can you add this function into the README and your personal map suggestion? Thanks a lot

**Comment by gianarb** [comment]
Thanks :+1:

**Pull request merged**
